name: 'Build LibreTV image'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build LibreTV image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 添加包写入权限

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: 'Set Docker image tag'
        id: set-tag
        run: |
          echo "IMAGE_NAME=tvpro" >> $GITHUB_OUTPUT

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.5.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.set-tag.outputs.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
