name: 'Build LibreTV image'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 'Build LibreTV image'
    runs-on: ubuntu-latest
    if: github.repository == 'LibreSpark/LibreTV' || github.repository == 'bestZwei/libretv1'

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: 'Set Docker image tag based on repository'
        id: set-tag
        run: |
          if [ "${{ github.repository }}" = "LibreSpark/LibreTV" ]; then
            echo "IMAGE_TAG=tvpro:latest" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=tvpro-beta:latest" >> $GITHUB_OUTPUT
          fi

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.5.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and push LibreTV image'
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "jiuyu6/${{ steps.set-tag.outputs.IMAGE_TAG }}"
          platforms: linux/amd64,linux/arm64/v8
